### ISSUE TITLE
Several inanimate entities have pronouns added

### ISSUE THREAD

**Issue by trinkey** [RoootTheFox/mob-pronouns#1]
painting, items, and item frames have it (armor stands too but that's fine imo)

there's probably more that i'm forgetting about

![image](https://github.com/RoootTheFox/mob-pronouns/assets/97406176/e3aa68a0-5aae-492e-be26-f97bb1f5f08d)

**Comment by RoootTheFox** [comment]
oops, forgot to check if its a living entity or not, my bad. will fix in a bit

**Comment by RoootTheFox** [comment]
should be fixed in 51084f3f6dc51ec8bb445bb64cea1faf5d6c0ce7, not sure if the mod builds though since i made the entire change in `nano` lol
